### ISSUE TITLE
Request for easy editor in Chatbot Module

### ISSUE THREAD

**Issue by 2br-2b** [Tadashi-Hikari/Sapphire-Assistant-Framework#2]
Could there be an easy way to let non-programmers help with the chatbot module? That way, they don't need as much experience coding, but the chatbot can be improved.

**Comment by Tadashi-Hikari** [comment]
I am very interested in making the Sapphire Assistant Framework customizable to non-programmers, but I am not certain where I could work in that functionality. I have not started on the chatbot module yet, but I intended it to be built out of machine learning libraries, which doesn't leave a ton of space for the non-technical. That said I am open to ideas if you have something in mind, and certainly a user could swap out the chatbot module with one that has a a more user friendly approach in terms of customization

**Comment by 2br-2b** [comment]
I had assumed that you had meant implementing a chatbot like Eliza.

What I was thinking is that if you ask the assistant "Tell me a joke", people could contribute their own jokes. If you ask it "How old are you" "Hello there", "This is the way", or "What is the average velocity of an unladen swallow", people could contribute answers to reference jokes from different franchises, memes, and other things to make the bot more fun for users who look for easter eggs.

**Comment by 2br-2b** [comment]
If something like this is easy to implement (which it seems to me to be), I could help manage this module once documentation on creating modules comes out.

**Comment by Tadashi-Hikari** [comment]
Absolutely. I am figuring out the best places to put a chat bot callback, and I am considering 3 hooks for it. The first would be on an error, the second would be on a reminder, and the 3rd would be callable by a skill. These ideas are of course preliminary, but I do expect chat bot functionality to be central to the application framework

**Comment by Tadashi-Hikari** [comment]
> I had assumed that you had meant implementing a chatbot like Eliza.
> 
> What I was thinking is that if you ask the assistant "Tell me a joke", people could contribute their own jokes. If you ask it "How old are you" "Hello there", "This is the way", or "What is the average velocity of an unladen swallow", people could contribute answers to reference jokes from different franchises, memes, and other things to make the bot more fun for users who look for easter eggs.

The 'callable' chat bot, which would give chat bot access would be driven by a NN/NLG framework. However, I do expect to have a STT module (since STT is native to Android) where it can read predefined responses (similar to Mycroft). There is no reason that multiple chat bot modules couldn't be installed alongside one another though, so you'd have an Eliza, Mycroft, and NLG stlye chat-bot setup to work with

**Comment by 2br-2b** [comment]
One option could be to have a static list of questions, like "how are you", "what is your name", and so on. Then, whenever a command is received, the bot checks to see if the command is in this list. If it finds the command, it won't check if the command should be run by a module, but instead simply retrieves the answer from the database and says that.

In the future, there may need to be a way for modules to override these commands, but at least for now, if we leave the commands them simple and specific, then we wouldn't run into any problems,

On the other hand (and I think this may work better), there could be a static list that is checked if a command doesn't fit into any of the modules. If it receives a command and it doesn't match up with any of the other modules, this could be a fallback, and if it doesn't find anything in this list that matches the statement, it responds with a catch-all of "I'm sorry - I don't understand that."

By the way, great job with the pre-alpha build! There's a lot of work that needs to go into it, but I'm looking forward to seeing Sapphire Assistant evolve!
