### ISSUE TITLE
Make the CoreSimpleActivity textView horizontally scrollable.

### ISSUE THREAD

**Issue by Tadashi-Hikari** [Tadashi-Hikari/Sapphire-Assistant-Framework#3]
I hate Android front end (I'm not very good at it yet), and for the life of me can't seem to get the TextView in CoreSimpleActivity to scroll horizontally. Help with that would be appreciated.

**Comment by anvaishy** [comment]
I would like to work on this issue

**Comment by Tadashi-Hikari** [comment]
That would be great. I didn't have a real purpose for a UI at this point, so I just have the android log print to a TextView with id: textView, which appends the new text using a broadcastReceiver anonymous inner class in CoreSimpleActivity.ky in the CoreModule. The core_activity under layout is what is inflated, and defines most of the parameters, with the exception of "set lHorizontallyScrolling = true" which is defined programtically in function thisOnCreate() in class CoreSimpleActivity.ky. This allows the text to avoid wrapping (better for readability) but for some reason the textView will not allow you to scroll horizontal to read the full text

**Comment by Tadashi-Hikari** [comment]
I merged in anvaishys change, hopefully it fixed it but I won't be around for a few days to try it. I'll leave this open until I can verify

**Comment by Tadashi-Hikari** [comment]
The change was resolved by using nested scroll views
