### ISSUE TITLE
A README or documentation detailing how it works and usage section would be appreciated!

### ISSUE THREAD

**Issue by shipsywor** [Tadashi-Hikari/Sapphire-Assistant-Framework#6]

**Comment by Tadashi-Hikari** [comment]
I'm going through and updating the documentation now. What would you find useful in a README and usage section

**Comment by Tadashi-Hikari** [comment]
@shipsywor I've gone through and added some guidance to the landing page, and touched up a few other wiki pages. Let me know what you think, and what else should be added or changed

**Comment by shipsywor** [comment]
Thank you! I will update you if there's something.
