### ISSUE TITLE
Consider f-droid inclusion

### ISSUE THREAD

**Issue by WPFilmmaker** [Tadashi-Hikari/Sapphire-Assistant-Framework#8]
Hi, it seems that the project is still in earl development (it looks like an amazing idea!), once you feel it is polished up enough, would you consider releasing it on f-droid? https://gitlab.com/fdroid/rfp/-/issues If you don't know it, f-droid is an appstore for FLOSS only apps and it would be great having an assistant there :)

**Comment by 2br-2b** [comment]
I absolutely want this also, but was waiting to open an issue until the project was further along.

**Comment by therealrobster** [comment]
Just throwing support for an fdroid release. Would be a great way to get it onto people's hands quickly and easily

**Comment by hikari-tadashi** [comment]
No problem! I intended to release it on F-Droid when its more stable. 100% on my radar
